import os

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_BLOCKED = "blocked"
STATUS_TRUE = True
STATUS_FALSE = False

TERMINAL_STATUS_LIST = [STATUS_ACTIVE, STATUS_INACTIVE]
SCREEN_SHOW_IS_ACTIVE_LIST = [STATUS_TRUE, STATUS_FALSE]

SESSION_STATUS_CHANGEABLE_LIST = [STATUS_ACTIVE, STATUS_INACTIVE]
SESSION_STATUS_LIST = [STATUS_ACTIVE, STATUS_INACTIVE, STATUS_BLOCKED]

AUDIO_FILE_ALLOWED_EXTENSIONS = ['mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac']